apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-example-azurefile
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: managed-azurefile-standard-lrs
