resource_group_name  = "chance-test-aks"
storage_account_name = "chance-test-standard-lrs-account"
container_name       = "chancetesttfstate"
prefix               = "chancetest"
location             = "canadacentral"
client_id            = "e685ae6c-73ff-4bfe-9cc6-27900d62c829"
user_ip              = "99.240.112.254"
